@Library('myLibrary') _
pipeline {
    agent any
    
    stages {
        
         stage('Checkout code from Git') {
            steps {   parallel(

              "1"  dir("tag_code1") {                              
                                         
                script {checkout_git.checkout_git("sparkjava-war-example", "master")}                
                }

               "2" dir("tag_code2") {                              
                                         
                script {checkout_git.checkout_git("java-hello-world-with-maven", "master")}                
                }
            )
            } 
        



        }

        stage('create tag on git repo') {
            steps {  parallel(                              
                 dir("tag_code1") {                        
                script {create_tag.create_tag("${tag}")}                
                 }
                  dir("tag_code2") {                        
                script {create_tag.create_tag("${tag}")}                
                 }
            )  
            }
        }
                                       
        
    }
 
}
