@Library('myLibrary') _
pipeline {
    agent any
    
    stages {
        
         stage('Checkout code from Git') {
            steps {     
                    
                 dir("tag_code1")
                {
                    script 

                     {checkout_git.checkout_git("sparkjava-war-example")}}
                
            } 
        



        }

        stage('create tag on git repo') {
            steps { 
                
                dir("tag_code1") {                        
                script {create_tag.create_tag("${tag}")}                
                 }
            
            }
        }
                                       
        
    }
 
}
