 @Library('myLibrary') _
pipeline {
    agent any
    
    stages {
        
         stage('Checkout code from Git') {
            steps {  

                dir("tag_code1") {                              
                                         
                script {checkout_git.checkout_git("java-hello-world-with-maven", "master")}                
                }
            }
        }

        stage('create tag on git repo') {
            steps {                                
                 dir("tag_code1") {                        
                script {create_tag.create_tag("${tag}")}                
                 }
            }
        }
                                       
        
    }

}
